# Copyright (C) 2017 ETH Zurich, University of Bologna and GreenWaves Technologies
# All rights reserved.
#
# This software may be modified and distributed under the terms
# of the BSD license.  See the LICENSE file for details.

PULP_APP = lcd_test
PULP_APP_FC_SRCS = test.c ../../Drivers/pulp_os/ili9341.c 
PULP_CFLAGS = -O2

include $(GAP_SDK_HOME)/tools/rules/pulp_rules.mk
