PULP_APP = test
PULP_APP_FC_SRCS = MultiRadio_main.c MultiRadio_Library.c MultiRadio_Callback.c Camera_Library.c Uart_Debug.c 
PULP_APP_HOST_SRCS = MultiRadio_main.c MultiRadio_Library.c MultiRadio_Callback.c Camera_Library.c Uart_Debug.c
#PULP_APP_FC_SRCS = test.c
PULP_CFLAGS = -O3 -g

# This tells the platform to activate what is needed to connect the debug bridge
#bridge=1
#override PULP_TEMPLATE_ARGS += camera(cpi0)

include $(PULP_SDK_HOME)/install/rules/pulp_rt.mk
